version: "3"

services:
  playground:
    build: .
    ports:
      - "4000:4000"
    networks:
      - "playground-network"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: example
      POSTGRES_DB: playground
    ports:
      - "5432:5432"
    volumes:
      - playground-volume:/var/lib/postgresql/data
    networks:
      - "playground-network"

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@localhost"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - "playground-network"

networks:
  playground-network:
    driver: bridge

volumes:
  playground-volume:
    driver: local
